///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LoginResponeAccount {
/*
{
  "hdBankUserId": "d214e527-3ccb-4a3e-bbff-15b2baed59ac",
  "fullName": "Huynh Huu Khanh",
  "username": "test13",
  "email": "khanh201011@gmail.com",
  "identityNumber": "123456789",
  "phone": "0123456789",
  "accountNo": "004704070000201",
  "id": 1,
  "createdAt": "2022-12-16T00:38:24.647775",
  "modifiedAt": "0001-01-01T00:00:00"
}
*/

  String? hdBankUserId;
  String? fullName;
  String? username;
  String? email;
  String? identityNumber;
  String? phone;
  String? accountNo;
  String? id;
  String? createdAt;
  String? modifiedAt;

  LoginResponeAccount({
    this.hdBankUserId,
    this.fullName,
    this.username,
    this.email,
    this.identityNumber,
    this.phone,
    this.accountNo,
    this.id,
    this.createdAt,
    this.modifiedAt,
  });
  LoginResponeAccount.fromJson(Map<String, dynamic> json) {
    hdBankUserId = json['hdBankUserId']?.toString();
    fullName = json['fullName']?.toString();
    username = json['username']?.toString();
    email = json['email']?.toString();
    identityNumber = json['identityNumber']?.toString();
    phone = json['phone']?.toString();
    accountNo = json['accountNo']?.toString();
    id = json['id']?.toString();
    createdAt = json['createdAt']?.toString();
    modifiedAt = json['modifiedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['hdBankUserId'] = hdBankUserId;
    data['fullName'] = fullName;
    data['username'] = username;
    data['email'] = email;
    data['identityNumber'] = identityNumber;
    data['phone'] = phone;
    data['accountNo'] = accountNo;
    data['id'] = id;
    data['createdAt'] = createdAt;
    data['modifiedAt'] = modifiedAt;
    return data;
  }
}

class LoginRespone {
/*
{
  "account": {
    "hdBankUserId": "d214e527-3ccb-4a3e-bbff-15b2baed59ac",
    "fullName": "Huynh Huu Khanh",
    "username": "test13",
    "email": "khanh201011@gmail.com",
    "identityNumber": "123456789",
    "phone": "0123456789",
    "accountNo": "004704070000201",
    "id": 1,
    "createdAt": "2022-12-16T00:38:24.647775",
    "modifiedAt": "0001-01-01T00:00:00"
  },
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwiQWNjb3VudE5vIjoiMDA0NzA0MDcwMDAwMjAxIiwibmJmIjoxNjcxMTI5Nzk4LCJleHAiOjE2NzExNzI5OTgsImlhdCI6MTY3MTEyOTc5OH0.QZfd_09GmUKny1o_ddvrDy3DtstCZt4UVwEipPCqhnY"
}
*/

  LoginResponeAccount? account;
  String? token;

  LoginRespone({
    this.account,
    this.token,
  });
  LoginRespone.fromJson(Map<String, dynamic> json) {
    account = (json['account'] != null) ? LoginResponeAccount.fromJson(json['account']) : null;
    token = json['token']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (account != null) {
      data['account'] = account!.toJson();
    }
    data['token'] = token;
    return data;
  }
}
