// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyTddYkuIWHXE9xJkTLPWvP9pywRSfu_Y',
    appId: '1:733640586662:web:d1ecc7834256f680fa8b67',
    messagingSenderId: '733640586662',
    projectId: 'pika-77947',
    authDomain: 'pika-77947.firebaseapp.com',
    storageBucket: 'pika-77947.appspot.com',
    measurementId: 'G-DWELGW6ZJP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXhqUb1HbjEtQihc6_e-whs_DZtUgBdqg',
    appId: '1:733640586662:android:f537920df862b2c6fa8b67',
    messagingSenderId: '733640586662',
    projectId: 'pika-77947',
    storageBucket: 'pika-77947.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdcAZuktsXGr5cVFi68ETkyY2dihlE0U8',
    appId: '1:733640586662:ios:3ddda8b33cfdbc3afa8b67',
    messagingSenderId: '733640586662',
    projectId: 'pika-77947',
    storageBucket: 'pika-77947.appspot.com',
    iosClientId: '733640586662-oh9082lm4nr01rau9r2rlic3cg43bk9g.apps.googleusercontent.com',
    iosBundleId: 'com.example.pika',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdcAZuktsXGr5cVFi68ETkyY2dihlE0U8',
    appId: '1:733640586662:ios:3ddda8b33cfdbc3afa8b67',
    messagingSenderId: '733640586662',
    projectId: 'pika-77947',
    storageBucket: 'pika-77947.appspot.com',
    iosClientId: '733640586662-oh9082lm4nr01rau9r2rlic3cg43bk9g.apps.googleusercontent.com',
    iosBundleId: 'com.example.pika',
  );
}
