///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CheckContactResponse {
/*
{
  "accountNo": "045704070000581",
  "fullName": "Pika Saving"
}
*/

  String? accountNo;
  String? fullName;

  CheckContactResponse({
    this.accountNo,
    this.fullName,
  });

  CheckContactResponse.fromJson(Map<String, dynamic> json) {
    accountNo = json['accountNo']?.toString();
    fullName = json['fullName']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['accountNo'] = accountNo;
    data['fullName'] = fullName;
    return data;
  }
}
